tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'jesseduffield/lazygit'
tap 'nicoverbruggen/homebrew-cask'


# Binaries
brew 'ant'
brew 'bash' 							# Latest Bash version
brew 'bats-core'
brew 'coreutils' 						# Those that come with macOS are outdated
brew 'curl'
brew 'duti'
brew 'exa'  							# Modern replacement for 'ls'
brew 'fd'								# Simple, fast and user-friendly alternative to find
brew 'gh'
brew 'git'								# Distributed revision control system
brew 'git-extras'
brew 'git-delta'						# Syntax-highlighting pager for git and diff output
brew 'gnupg'
brew 'grep'
brew 'krb5'
brew 'libpq'
brew 'mackup'
brew 'mas' 								# Mac App Store command-line interface
brew 'openssl'
brew 'pkg-config' 						# https://github.com/driesvints/dotfiles/issues/20
brew 'pyenv'  							# Python version management
brew 'ssh-copy-id'
brew 'stow'
brew 'svn'								# Needed to install fonts
brew 'terminal-notifier' 				# Send macOS User Notifications from the command-line
brew 'telnet'
brew 'tree'								# List the contents of directories in an intuitive way
brew 'tmux'								# Terminal multiplexer
brew 'wget'								# Internet file retriever
brew 'zsh'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'


# Development
brew 'composer'
brew 'fnm'
brew 'mysql'
brew 'node'
brew 'php'
brew 'php@8.2'
brew 'phpunit'
brew 'redis'
brew 'yarn'


# Media
brew 'ffmpeg'
brew 'imagemagick'
brew 'uni'
brew 'webp'
brew 'youtube-dl'


# Mac App Store
mas 'Amphetamine',  id: 937984704
mas 'Spark', 		id: 1176895641
mas 'Speedtest', 	id: 1153157709
